Unifik\SystemBundle\Entity\AppTranslation:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      gedmo:
        - sluggable
    active:
      type: boolean
      nullable: true