Flexy\SystemBundle\Entity\Login:
  type: entity
  repositoryClass: Flexy\SystemBundle\Entity\MappingRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    username:
      type: string
      length: 255
    ip:
      type: string
      length: 16
    success:
      type: boolean
