Unifik\SystemBundle\Entity\Mapping:
  type: entity
  repositoryClass: Unifik\SystemBundle\Entity\MappingRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    type:
      type: string
      length: 255
    target:
      type: string
      length: 255
    ordering:
      type: integer
      nullable: true
  manyToOne:
    section:
      targetEntity: Unifik\SystemBundle\Entity\Section
      inversedBy:  mappings
      joinColumn:
        name: section_id
        referencedColumnName: id
        onDelete: cascade
    app:
      targetEntity: Unifik\SystemBundle\Entity\App
      inversedBy:  mappings
      joinColumn:
        name: app_id
        referencedColumnName: id
        onDelete: cascade
    navigation:
      targetEntity: Unifik\SystemBundle\Entity\Navigation
      inversedBy:  mappings
      joinColumn:
        name: navigation_id
        referencedColumnName: id
        onDelete: cascade