Flexy\SystemBundle\Entity\Navigation:
  type: entity
  repositoryClass: Flexy\SystemBundle\Entity\NavigationRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    code:
      type: string
      length: 255
    name:
      type: string
      length: 255
  oneToMany:
    sectionNavigations:
      targetEntity: Flexy\SystemBundle\Entity\SectionNavigation
      mappedBy: navigation
    mappings:
      targetEntity: Flexy\SystemBundle\Entity\Mapping
      mappedBy: navigation
  manyToOne:
    app:
      targetEntity: Flexy\SystemBundle\Entity\App
      inversedBy: navigations
      joinColumn:
        name: app_id
        referencedColumnName: id
        onDelete: cascade