Egzakt\SystemBundle\Entity\RoleTranslation:
  type: entity
  indexes:
    role_translation_idx:
      columns: [locale, translatableId]
  uniqueConstraints:
    role_translation_unique_idx:
      columns: [locale, translatableId]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    locale:
      type: string
      length: 5
    name:
      type: string
      length: 255
      nullable: true
  manyToOne:
    translatable:
      targetEntity: Egzakt\SystemBundle\Entity\Role
      inversedBy:  translations
      joinColumn:
        name: translatableId
        referencedColumnName: id
        onDelete:  cascade
