Egzakt\SystemBundle\Entity\SectionTranslation:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    locale:
      type: string
      length: 5
    name:
      type: string
      length: 255
      nullable: true
      gedmo:
        - sluggable
    slug:
      type: string
      length: 255
      nullable: true
      gedmo:
        slug:
          fields: [name]
          separator: -
    pageTitle:
      type: string
      length: 255
      nullable: true
    headCode:
      type: text
      nullable: true
    active:
      type: boolean
      nullable: true