Unifik\SystemBundle\Entity\SectionTranslation:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
    active:
      type: boolean
      nullable: true