Egzakt\SystemBundle\Entity\SectionNavigation:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    ordering:
      type: integer
      nullable: true
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
  repositoryClass: Egzakt\SystemBundle\Entity\SectionNavigationRepository
  manyToOne:
    section:
      targetEntity: Egzakt\SystemBundle\Entity\Section
      inversedBy:  sectionNavigations
      joinColumn:
        name: section_id
        referencedColumnName: id
        onDelete:  cascade
    navigation:
      targetEntity: Egzakt\SystemBundle\Entity\Navigation
      inversedBy:  sectionNavigations
      joinColumn:
        name: navigation_id
        referencedColumnName: id
        onDelete:  cascade
  uniqueConstraints:
    section_navigation:
      columns: [ section_id, navigation_id ]
