Egzakt\SystemBundle\Entity\TextTranslation:
  type: entity
#  indexes:
#    text_translation_idx:
#      columns: [locale, translatable_id]
#  uniqueConstraints:
#    text_translation_unique_idx:
#      columns: [locale, translatable_id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    locale:
      type: string
      length: 5
    text:
      type: text
    name:
      type: string
      length: 255
      nullable: true
    anchor:
      type: string
      length: 255
      nullable: true
    active:
      type: boolean
      nullable: true
#  manyToOne:
#    translatable:
#      targetEntity: Egzakt\SystemBundle\Entity\Text
#      inversedBy:  translations
#      joinColumn:
#        name: translatable_id
#        referencedColumnName: id
#        onDelete:  cascade