flexy_system_frontend_home:
    pattern:  /
    defaults: { _controller: "FlexySystemBundle:Frontend/Home:index" }

flexy_system_frontend_text:
    pattern:  /{sectionsPath}
    defaults: { _controller: "FlexySystemBundle:Frontend/Text:index" }
