# Security
unifik_system_backend_login:
    pattern:  /login
    defaults: { _controller: "UnifikSystemBundle:Backend/Security:login", _locale: %locale% } # force default locale

unifik_system_backend_login_check:
    pattern:  /login-check
    options:  { i18n: false }

unifik_system_backend_logout:
    pattern:  /logout
    defaults: { _controller: "UnifikSystemBundle:Backend/Security:logout" }

# Home
unifik_system_backend_dashboard:
    pattern:  /
    defaults: { _controller: "UnifikSystemBundle:Backend/Dashboard:index" }

unifik_system_backend_switch_managed_app:
    pattern:  /managed-application/{appSlug}
    defaults: { _controller: "UnifikSystemBundle:Backend/Dashboard:index" }

# Help
unifik_system_backend_help_detail:
    pattern:  /help/{itemId}
    defaults: { _controller: "UnifikSystemBundle:Backend/Dashboard:helpDetail" }

unifik_system_backend_help:
    pattern:  /help
    defaults: { _controller: "UnifikSystemBundle:Backend/Dashboard:help" }

# Users
unifik_system_backend_user:
    pattern:  /users
    defaults: { _controller: "UnifikSystemBundle:Backend/User/User:index" }

unifik_system_backend_user_edit:
    pattern:  /users/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/User/User:edit", id: 0 }

unifik_system_backend_user_delete_check:
    pattern:  /users/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/User/User:checkDelete" }

unifik_system_backend_user_delete:
    pattern:  /users/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/User/User:delete" }

# Roles
unifik_system_backend_role:
    pattern:  /roles
    defaults: { _controller: "UnifikSystemBundle:Backend/Role/Role:index" }

unifik_system_backend_role_edit:
    pattern:  /roles/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Role/Role:edit", id: 0 }

unifik_system_backend_role_delete:
    pattern:  /roles/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Role/Role:delete" }

unifik_system_backend_role_delete_check:
    pattern:  /roles/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Role/Role:checkDelete" }

# Members
unifik_system_backend_member:
    pattern:  /members
    defaults: { _controller: "UnifikSystemBundle:Backend/Member/Member:list" }

unifik_system_backend_member_edit:
    pattern:  /members/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Member/Member:edit", id: 0 }

unifik_system_backend_member_delete:
    pattern:  /members/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Member/Member:delete" }

# Texts
unifik_system_backend_text:
    pattern:  /texts/{sectionId}
    defaults: { _controller: "UnifikSystemBundle:Backend/Text/Text:index" }

unifik_system_backend_text_order:
    pattern:  /texts/{sectionId}/order
    defaults: { _controller: "UnifikSystemBundle:Backend/Text/Text:order" }

unifik_system_backend_text_edit:
    pattern:  /texts/{sectionId}/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Text/Text:edit", id: 0 }

unifik_system_backend_text_delete:
    pattern:  /texts/{sectionId}/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Text/Text:delete" }

unifik_system_backend_text_delete_check:
    pattern:  /texts/{sectionId}/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Text/Text:checkDelete" }

# Sections (roots handling)
unifik_system_backend_section_root:
    pattern:  /sections/{appSlug}/root
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Root:list" }

unifik_system_backend_section_root_order:
    pattern:  /sections/{appSlug}/root/order
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Root:order" }

unifik_system_backend_section_root_edit:
    pattern:  /sections/{appSlug}/root/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Root:edit", id: 0 }

unifik_system_backend_section_root_delete:
    pattern:  /sections/{appSlug}/root/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Root:delete" }

unifik_system_backend_section_root_delete_check:
    pattern:  /sections/{appSlug}/root/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Root:checkDelete" }

# Sections
unifik_system_backend_section:
    pattern:  /sections/{sectionId}
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Section:index" }

unifik_system_backend_section_order:
    pattern:  /sections/{sectionId}/order
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Section:order" }

unifik_system_backend_section_edit:
    pattern:  /sections/{sectionId}/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Section:edit", id: 0 }

unifik_system_backend_section_delete:
    pattern:  /sections/{sectionId}/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Section:delete" }

unifik_system_backend_section_delete_check:
    pattern:  /sections/{sectionId}/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Section/Section:checkDelete" }

# Locales
unifik_system_backend_locale:
    pattern:  /locales
    defaults: { _controller: "UnifikSystemBundle:Backend/Locale/Locale:list" }

unifik_system_backend_locale_order:
    pattern:  /locales/order
    defaults: { _controller: "UnifikSystemBundle:Backend/Locale/Locale:order" }

unifik_system_backend_locale_edit:
    pattern:  /locales/{id}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Locale/Locale:edit", id: 0 }

unifik_system_backend_locale_delete:
    pattern:  /locales/{id}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Locale/Locale:delete" }

unifik_system_backend_locale_delete_check:
    pattern:  /locales/{id}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Locale/Locale:checkDelete" }
    
# Applications
unifik_system_backend_application:
    pattern:  /applications
    defaults: { _controller: "UnifikSystemBundle:Backend/Application/Application:list" }

unifik_system_backend_application_edit:
    pattern:  /applications/{applicationId}/edit
    defaults: { _controller: "UnifikSystemBundle:Backend/Application/Application:edit", applicationId: 0 }

unifik_system_backend_application_delete:
    pattern:  /applications/{applicationId}/delete
    defaults: { _controller: "UnifikSystemBundle:Backend/Application/Application:delete" }

unifik_system_backend_application_delete_check:
    pattern:  /applications/{applicationId}/delete/check
    defaults: { _controller: "UnifikSystemBundle:Backend/Application/Application:checkDelete" }

# Translation Editor
unifik_system_backend_translation:
    pattern:  /translation-editor
    defaults: { _controller: "UnifikSystemBundle:Backend/Translation/Translation:list" }

unifik_system_backend_translation_insert:
    pattern:  /translation-editor/insert
    defaults: { _controller: "UnifikSystemBundle:Backend/Translation/Translation:insert" }

unifik_system_backend_translation_rebuild_token:
    pattern:  /translation-editor/rebuild-tokens
    defaults: { _controller: "UnifikSystemBundle:Backend/Translation/Translation:rebuildToken" }

unifik_system_backend_quickcreatejs:
    pattern:  /quickCreate.js
    defaults: { _controller: "UnifikSystemBundle:Backend/Javascripts:quickCreate" }
    options:
        expose: true