# Security
egzakt_system_backend_login:
    pattern:  /login
    defaults: { _controller: "EgzaktSystemBundle:Backend/Security:login" }

egzakt_system_backend_login_check:
    pattern:  /login-check
    options:  { i18n: false }

egzakt_system_backend_logout:
    pattern:  /logout
    defaults: { _controller: "EgzaktSystemBundle:Backend/Security:logout" }

# Home
egzakt_system_backend_dashboard:
    pattern:  /
    defaults: { _controller: "EgzaktSystemBundle:Backend/Dashboard:index" }

egzakt_system_backend_app:
    pattern:  /app/{appSlug}
    defaults: { _controller: "EgzaktSystemBundle:Backend/Dashboard:index" }

# Help
egzakt_system_backend_help_detail:
    pattern:  /help/{itemId}
    defaults: { _controller: "EgzaktSystemBundle:Backend/Dashboard:helpDetail" }

egzakt_system_backend_help:
    pattern:  /help
    defaults: { _controller: "EgzaktSystemBundle:Backend/Dashboard:help" }

# Users
egzakt_system_backend_user:
    pattern:  /users
    defaults: { _controller: "EgzaktSystemBundle:Backend/User/User:index" }

egzakt_system_backend_user_edit:
    pattern:  /users/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/User/User:edit", id: 0 }

egzakt_system_backend_user_delete:
    pattern:  /users/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/User/User:delete" }

# Roles
egzakt_system_backend_role:
    pattern:  /roles
    defaults: { _controller: "EgzaktSystemBundle:Backend/Role/Role:index" }

egzakt_system_backend_role_edit:
    pattern:  /roles/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Role/Role:edit", id: 0 }

egzakt_system_backend_role_delete:
    pattern:  /roles/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Role/Role:delete" }

# Members
egzakt_system_backend_member:
    pattern:  /members
    defaults: { _controller: "EgzaktSystemBundle:Backend/Member/Member:list" }

egzakt_system_backend_member_edit:
    pattern:  /members/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Member/Member:edit", id: 0 }

egzakt_system_backend_member_delete:
    pattern:  /members/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Member/Member:delete" }

# Texts
egzakt_system_backend_text:
    pattern:  /texts/{sectionId}
    defaults: { _controller: "EgzaktSystemBundle:Backend/Text/Text:index" }

egzakt_system_backend_text_order:
    pattern:  /texts/{sectionId}/order
    defaults: { _controller: "EgzaktSystemBundle:Backend/Text/Text:order" }

egzakt_system_backend_text_edit:
    pattern:  /texts/{sectionId}/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Text/Text:edit", id: 0 }

egzakt_system_backend_text_delete:
    pattern:  /texts/{sectionId}/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Text/Text:delete" }

# Sections (roots handling)
egzakt_system_backend_section_root:
    pattern:  /sections/{appSlug}/root
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Root:list" }

egzakt_system_backend_section_root_order:
    pattern:  /sections/{appSlug}/root/order
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Root:order" }

egzakt_system_backend_section_root_edit:
    pattern:  /sections/{appSlug}/root/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Root:edit", id: 0 }

egzakt_system_backend_section_root_delete:
    pattern:  /sections/{appSlug}/root/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Root:delete" }

# Sections
egzakt_system_backend_section:
    pattern:  /sections/{sectionId}
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Section:index" }

egzakt_system_backend_section_order:
    pattern:  /sections/{sectionId}/order
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Section:order" }

egzakt_system_backend_section_edit:
    pattern:  /sections/{sectionId}/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Section:edit", id: 0 }

egzakt_system_backend_section_delete:
    pattern:  /sections/{sectionId}/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Section/Section:delete" }

# Locales
egzakt_system_backend_locale:
    pattern:  /locales
    defaults: { _controller: "EgzaktSystemBundle:Backend/Locale/Locale:list" }

egzakt_system_backend_locale_order:
    pattern:  /locales/order
    defaults: { _controller: "EgzaktSystemBundle:Backend/Locale/Locale:order" }

egzakt_system_backend_locale_edit:
    pattern:  /locales/{id}/edit
    defaults: { _controller: "EgzaktSystemBundle:Backend/Locale/Locale:edit", id: 0 }

egzakt_system_backend_locale_delete:
    pattern:  /locales/{id}/delete
    defaults: { _controller: "EgzaktSystemBundle:Backend/Locale/Locale:delete" }