parameters:

    egzakt_system.kernel_controller_listener.class:       Egzakt\SystemBundle\Listener\ControllerListener
    egzakt_system.kernel_response_listener.class:         Egzakt\SystemBundle\Listener\ResponseListener
    egzakt_system.post_load_listener.class:               Egzakt\SystemBundle\Listener\PostLoadListener
    egzakt_system.kernel_exception_listener.class:        Egzakt\SystemBundle\Listener\ExceptionListener
    egzakt_system.core.class:                             Egzakt\SystemBundle\Lib\Core
    egzakt_system.helper.class:                           Egzakt\SystemBundle\Lib\Helper
    egzakt_system.twig_extension.class:                   Egzakt\SystemBundle\Extensions\TwigExtension
    egzakt_system.twig_translation_extension.class:       Egzakt\SystemBundle\Extensions\TranslationExtension
    egzakt_system.inspect_extension.class:                Egzakt\SystemBundle\Extensions\InspectExtension
    egzakt_system.navigation_builder.class:               Egzakt\SystemBundle\Lib\NavigationBuilder
    egzakt_system.navigation_item.class:                  Egzakt\SystemBundle\Lib\NavigationItem
    egzakt_system.breadcrumbs.class:                      Egzakt\SystemBundle\Lib\Breadcrumbs
    egzakt_system.page_title.class:                       Egzakt\SystemBundle\Lib\PageTitle
    egzakt_system.router_invalidator.class:               Egzakt\SystemBundle\Lib\RouterInvalidator
    egzakt_system.router_auto_parameters_handler.class:   Egzakt\SystemBundle\Lib\RouterAutoParametersHandler
    egzakt_system.section_filter.class:                   Egzakt\SystemBundle\Lib\SectionFilter
    egzakt_system.tree_entity_orderer.class:              Egzakt\SystemBundle\Lib\TreeEntityOrderer
    egzakt_system.form.type.tree_choice.class:            Egzakt\SystemBundle\Form\Type\TreeChoiceType
    egzakt_system.locale_switcher.class:                  Egzakt\SystemBundle\Lib\LocaleSwitcher
    egzakt_backend.security.cms_voter.class:              Egzakt\SystemBundle\Lib\Backend\CmsVoter
    egzakt_backend.core.class:                            Egzakt\SystemBundle\Lib\Backend\Core
    egzakt_backend.form.type.advanced_file.class:         Egzakt\SystemBundle\Form\Backend\AdvancedFileType
    egzakt_frontend.core.class:                           Egzakt\SystemBundle\Lib\Frontend\Core
    egzakt_system.deletable.class:                        Egzakt\SystemBundle\Lib\DeletableService
    egzakt_system.deletable_user_listener.class:          Egzakt\SystemBundle\Listener\UserDeletableListener

services:

    egzakt_system.deletable:
        class: %egzakt_system.deletable.class%

    egazkt_system.deletable_user_listener:
        class: %egzakt_system.deletable_user_listener.class%
        arguments: [ @security.context ]
        tags:
          - { name: egzakt_system.deletable, entity: Egzakt\SystemBundle\Entity\User }

    egzakt_system.kernel_controller_listener:
        class: %egzakt_system.kernel_controller_listener.class%
        tags:
          - { name: kernel.event_listener, event: kernel.controller }
        calls:
          - [ setContainer, [ @service_container ] ]

    egzakt_system.post_load_listener:
        class: %egzakt_system.post_load_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad }
        calls:
          - [ setContainer, [ @service_container ] ]

    egzakt_system.kernel_exception_listener:
        class: %egzakt_system.kernel_exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        calls:
            - [ setKernel, [ @kernel ] ]
            - [ setTemplating, [ @templating ] ]

    egzakt_system.core:
        class: %egzakt_system.core.class%

    egzakt_system.twig_extension:
        class: %egzakt_system.twig_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setRequest, [ @?request= ] ]
          - [ setLocale, [ %locale% ] ]
          - [ setSystemCore, [ @egzakt_system.core ] ]

    egzakt_system.twig_translation_extension:
        class: %egzakt_system.twig_translation_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setDoctrine, [ @doctrine ] ]

    egzakt_system.inspect_extension:
        class: %egzakt_system.inspect_extension.class%
        tags:
          - { name: twig.extension }

    egzakt_system.navigation_builder:
        scope: prototype
        class: %egzakt_system.navigation_builder.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    egzakt_system.navigation_item:
        scope: prototype
        class: %egzakt_system.navigation_item.class%

    egzakt_system.breadcrumbs:
        shared: true
        class:  %egzakt_system.breadcrumbs.class%

    egzakt_system.page_title:
        shared: true
        class:  %egzakt_system.page_title.class%

    egzakt_system.pre_persist_listener:
        class: Egzakt\SystemBundle\Listener\DoctrineEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }


    egzakt_system.router_invalidator:
        class: %egzakt_system.router_invalidator.class%
        arguments: [ @kernel ]

    egzakt_system.router_auto_parameters_handler:
        class: %egzakt_system.router_auto_parameters_handler.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    egzakt_system.locale_switcher:
        class: %egzakt_system.locale_switcher.class%
        arguments: [@service_container]

    egzakt_backend.core:
        class:  %egzakt_backend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setSession, [ @session= ] ]
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @egzakt_system.breadcrumbs ] ]
          - [ setPageTitle, [ @egzakt_system.page_title ] ]
          - [ setLocale, [ %locale% ] ]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    egzakt_system.form.type.advanced_file:
        class: %egzakt_backend.form.type.advanced_file.class%
        tags:
          - { name: form.type, alias: advanced_file }

    egzakt_frontend.core:
        class:  %egzakt_frontend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @egzakt_system.breadcrumbs ] ]
          - [ setPageTitle, [ @egzakt_system.page_title ] ]
          
    egzakt_system.tree_entity_orderer:
        class: %egzakt_system.tree_entity_orderer.class%

    egzakt_system.form.type.tree_choice:
        class: %egzakt_system.form.type.tree_choice.class%
        arguments: [@egzakt_system.tree_entity_orderer]
        tags:
            - { name: form.type, alias: tree_choice }

    egzakt_system.section_filter:
        class: %egzakt_system.section_filter.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]

    egzakt_system.security.cms_voter:
        class: %egzakt_backend.security.cms_voter.class%
        arguments: [@service_container]
        tags:
            - { name: security.voter }