parameters:

    flexy_system.kernel_controller_listener.class:             Flexy\SystemBundle\Listener\ControllerListener
    flexy_system.kernel_response_listener.class:               Flexy\SystemBundle\Listener\ResponseListener
    flexy_system.post_load_listener.class:                     Flexy\SystemBundle\Listener\PostLoadListener
    flexy_system.kernel_exception_listener.class:              Flexy\SystemBundle\Listener\ExceptionListener
    flexy_system.core.class:                                   Flexy\SystemBundle\Lib\Core
    flexy_system.twig_extension.class:                         Flexy\SystemBundle\Extensions\TwigExtension
    flexy_system.twig_translation_extension.class:             Flexy\SystemBundle\Extensions\TranslationExtension
    flexy_system.inspect_extension.class:                      Flexy\SystemBundle\Extensions\InspectExtension
    flexy_system.navigation_builder.class:                     Flexy\SystemBundle\Lib\NavigationBuilder
    flexy_system.navigation_item.class:                        Flexy\SystemBundle\Lib\NavigationItem
    flexy_system.breadcrumbs.class:                            Flexy\SystemBundle\Lib\Breadcrumbs
    flexy_system.page_title.class:                             Flexy\SystemBundle\Lib\PageTitle
    flexy_system.router_invalidator.class:                     Flexy\SystemBundle\Lib\RouterInvalidator
    flexy_system.router_auto_parameters_handler.class:         Flexy\SystemBundle\Lib\RouterAutoParametersHandler
    flexy_system.section_filter.class:                         Flexy\SystemBundle\Lib\SectionFilter
    flexy_system.tree_entity_orderer.class:                    Flexy\SystemBundle\Lib\TreeEntityOrderer
    flexy_system.form.type.tree_choice.class:                  Flexy\SystemBundle\Form\Type\TreeChoiceType
    flexy_system.deletable.class:                              Flexy\SystemBundle\Lib\DeletableService
    flexy_system.deletable_user_listener.class:                Flexy\SystemBundle\Listener\UserDeletableListener
    flexy_system.deletable_role_listener.class:                Flexy\SystemBundle\Listener\RoleDeletableListener
    flexy_system.deletable_section_listener.class:             Flexy\SystemBundle\Listener\SectionDeletableListener
    flexy_system.deletable_app_listener.class:                 Flexy\SystemBundle\Listener\AppDeletableListener
    flexy_system.locale_switcher.class:                        Flexy\SystemBundle\Lib\LocaleSwitcher
    flexy_system.section_translation.sluggable.listener.class: Flexy\SystemBundle\Lib\SectionTranslationSluggableListener
    flexy_system.form.type.creatable_entity.class:             Flexy\SystemBundle\Form\Type\CreatableEntityType
    flexy_backend.security.cms_voter.class:                    Flexy\SystemBundle\Lib\Backend\CmsVoter
    flexy_backend.core.class:                                  Flexy\SystemBundle\Lib\Backend\Core
    flexy_backend.form.type.advanced_file.class:               Flexy\SystemBundle\Form\Backend\AdvancedFileType
    flexy_backend.login_listener.class:                        Flexy\SystemBundle\Listener\LoginBackendListener
    flexy_frontend.core.class:                                 Flexy\SystemBundle\Lib\Frontend\Core

services:

    flexy_system.deletable:
        class: %flexy_system.deletable.class%

    egazkt_system.deletable_user_listener:
        class: %flexy_system.deletable_user_listener.class%
        arguments: [ @security.context ]
        tags:
          - { name: flexy_system.deletable, entity: Flexy\SystemBundle\Entity\User }

    egazkt_system.deletable_role_listener:
        class: %flexy_system.deletable_role_listener.class%
        tags:
          - { name: flexy_system.deletable, entity: Flexy\SystemBundle\Entity\Role }

    egazkt_system.deletable_section_listener:
        class: %flexy_system.deletable_section_listener.class%
        tags:
          - { name: flexy_system.deletable, entity: Flexy\SystemBundle\Entity\Section }

    egazkt_system.deletable_app_listener:
        class: %flexy_system.deletable_app_listener.class%
        tags:
          - { name: flexy_system.deletable, entity: Flexy\SystemBundle\Entity\App }

    flexy_system.kernel_controller_listener:
        class: %flexy_system.kernel_controller_listener.class%
        tags:
          - { name: kernel.event_listener, event: kernel.controller }
        calls:
          - [ setContainer, [ @service_container ] ]

    flexy_system.post_load_listener:
        class: %flexy_system.post_load_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad }
        calls:
          - [ setContainer, [ @service_container ] ]

    flexy_system.kernel_exception_listener:
        class: %flexy_system.kernel_exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        calls:
            - [ setKernel, [ @kernel ] ]
            - [ setTemplating, [ @templating ] ]

    flexy_system.core:
        class: %flexy_system.core.class%

    flexy_system.twig_extension:
        class: %flexy_system.twig_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setRequest, [ @?request= ] ]
          - [ setLocale, [ %locale% ] ]
          - [ setSystemCore, [ @flexy_system.core ] ]

    flexy_system.twig_translation_extension:
        class: %flexy_system.twig_translation_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setDoctrine, [ @doctrine ] ]

    flexy_system.inspect_extension:
        class: %flexy_system.inspect_extension.class%
        tags:
          - { name: twig.extension }

    flexy_system.navigation_builder:
        scope: prototype
        class: %flexy_system.navigation_builder.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    flexy_system.navigation_item:
        scope: prototype
        class: %flexy_system.navigation_item.class%

    flexy_system.breadcrumbs:
        shared: true
        class:  %flexy_system.breadcrumbs.class%

    flexy_system.page_title:
        shared: true
        class:  %flexy_system.page_title.class%

    flexy_system.pre_persist_listener:
        class: Flexy\SystemBundle\Listener\DoctrineEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    flexy_system.router_invalidator:
        class: %flexy_system.router_invalidator.class%
        arguments: [ @kernel ]

    flexy_system.router_auto_parameters_handler:
        class: %flexy_system.router_auto_parameters_handler.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    flexy_system.locale_switcher:
        class: %flexy_system.locale_switcher.class%
        arguments: [@service_container]

    flexy_system.form.type.creatable_entity:
        class: %flexy_system.form.type.creatable_entity.class%
        tags:
            - { name: form.type, alias: creatable_entity }

    flexy_backend.core:
        class:  %flexy_backend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setSession, [ @session= ] ]
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @flexy_system.breadcrumbs ] ]
          - [ setPageTitle, [ @flexy_system.page_title ] ]
          - [ setLocale, [ %locale% ] ]

    flexy_backend.login_listener:
        class: %flexy_backend.login_listener.class%
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    flexy_system.form.type.advanced_file:
        class: %flexy_backend.form.type.advanced_file.class%
        tags:
          - { name: form.type, alias: advanced_file }

    flexy_frontend.core:
        class:  %flexy_frontend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @flexy_system.breadcrumbs ] ]
          - [ setPageTitle, [ @flexy_system.page_title ] ]
          
    flexy_system.tree_entity_orderer:
        class: %flexy_system.tree_entity_orderer.class%

    flexy_system.form.type.tree_choice:
        class: %flexy_system.form.type.tree_choice.class%
        arguments: [@flexy_system.tree_entity_orderer]
        tags:
            - { name: form.type, alias: tree_choice }

    flexy_system.section_filter:
        class: %flexy_system.section_filter.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]

    flexy_system.security.cms_voter:
        class: %flexy_backend.security.cms_voter.class%
        arguments: [@service_container]
        tags:
            - { name: security.voter }

    flexy_system.section_translation.sluggable.listener:
        class: %flexy_system.section_translation.sluggable.listener.class%
        tags:
            - { name: doctrine.event_subscriber, type: sluggable, entity: Flexy\SystemBundle\Entity\SectionTranslation }