Egzakt\SystemBundle\Entity\Member:
    properties:
        firstname:
            - NotBlank: { groups: [Default, edit, register] }
        lastname:
            - NotBlank: { groups: [Default, edit, register] }
        email:
            - Email: { groups: [Default, forgot_password, edit, register] }
            - NotBlank: { groups: [Default, forgot_password, edit, register] }
        password:
            - NotBlank: { groups: [reset_password, register] }
    constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: email, groups: [Default, edit, register] }

Egzakt\SystemBundle\Entity\User:
    properties:
        username:
            - NotBlank: { groups: [new, edit] }
            - Length: { groups: [new, edit], min: 3, minMessage: This field must be at least 3 characters long }
        firstname:
            - NotBlank: { groups: [new, edit] }
        lastname:
            - NotBlank: { groups: [new, edit] }
        email:
            - Email: { groups: [new, edit, forgot_password] }
            - NotBlank: { groups: [new, edit, forgot_password] }
        password:
            - NotBlank: { groups: [new, reset_password] }
            - Length: { groups: [new, edit, reset_password], min: 8, minMessage: Password must be at least 8 characters long }
        roles:
            - Count: { groups: [new, edit], min: 1, minMessage: You must select at least 1 role }
    constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: username, groups: [new, edit] }
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: email, groups: [new, edit]  }

Egzakt\SystemBundle\Entity\SectionTranslation:
    properties:
        name:
            - NotBlank: { groups: [Default] }

Egzakt\SystemBundle\Entity\Section:
    constraints:
      - Callback:
          methods: [isHeadCodeHtml]

Egzakt\SystemBundle\Entity\TextTranslation:
    properties:
        text:
            - NotBlank: ~
    constraints:
        - Callback:
            methods: [isCollapsableValid]

Egzakt\SystemBundle\Entity\RoleTranslation:
    properties:
        name:
            - NotBlank: ~

Egzakt\SystemBundle\Entity\Locale:
    properties:
        name:
            - NotBlank: ~
        code:
            - NotBlank: ~