<?php

namespace Egzakt\SystemBundle\Entity;

use Egzakt\SystemBundle\Lib\BaseEntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends BaseEntityRepository
{

    public function findOrCreate($id, Section $section)
    {
        $text = $this->find($id);
        if ( null === $text ) {
            $text = new Text();
            $text->setContainer($this->container);
            $text->setSection($section);
        }

        return $text;
    }
}
